/* Generated by wbuild from "MenuBar.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfMenuBar_H_
#define _XfwfMenuBar_H_
#include <Xfwf/Rows.h>
_XFUNCPROTOBEGIN
Boolean  XfwfCallProcessMenu(
#if NeedFunctionPrototypes
Widget,Widget ,Cursor 
#endif
);
typedef struct _XfwfMenuBarClassRec *XfwfMenuBarWidgetClass;
typedef struct _XfwfMenuBarRec *XfwfMenuBarWidget;
externalref WidgetClass xfwfMenuBarWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfMenuBar_H_*/
