/* Generated by wbuild from "RadioGrp.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfRadioGroup_H_
#define _XfwfRadioGroup_H_
#include <Xfwf/Group.h>
_XFUNCPROTOBEGIN
#include <Xfwf/Converters.h>
#ifndef XtNlabels
#define XtNlabels "labels"
#endif
#ifndef XtCLabels
#define XtCLabels "Labels"
#endif
#ifndef XtRStringArray
#define XtRStringArray "StringArray"
#endif

typedef struct _XfwfRadioGroupClassRec *XfwfRadioGroupWidgetClass;
typedef struct _XfwfRadioGroupRec *XfwfRadioGroupWidget;
externalref WidgetClass xfwfRadioGroupWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfRadioGroup_H_*/
