/* Generated by wbuild from "Enforcer.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfEnforcer_H_
#define _XfwfEnforcer_H_
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
typedef struct _XfwfEnforcerClassRec *XfwfEnforcerWidgetClass;
typedef struct _XfwfEnforcerRec *XfwfEnforcerWidget;
externalref WidgetClass xfwfEnforcerWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfEnforcer_H_*/
