/* Generated by wbuild from "VScrollb.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfVScrollbar_H_
#define _XfwfVScrollbar_H_
#include <Xfwf/Scrollbar.h>
_XFUNCPROTOBEGIN
typedef struct _XfwfVScrollbarClassRec *XfwfVScrollbarWidgetClass;
typedef struct _XfwfVScrollbarRec *XfwfVScrollbarWidget;
externalref WidgetClass xfwfVScrollbarWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfVScrollbar_H_*/
