/* Generated by wbuild from "Icon.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfIcon_H_
#define _XfwfIcon_H_
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
#include <Xfwf/Converters.h>
#ifndef XtNimage
#define XtNimage "image"
#endif
#ifndef XtCImage
#define XtCImage "Image"
#endif
#ifndef XtRIcon
#define XtRIcon "Icon"
#endif

#ifndef XtNactivate
#define XtNactivate "activate"
#endif
#ifndef XtCActivate
#define XtCActivate "Activate"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XfwfIconClassRec *XfwfIconWidgetClass;
typedef struct _XfwfIconRec *XfwfIconWidget;
externalref WidgetClass xfwfIconWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfIcon_H_*/
