/* Generated by wbuild from "XmIcon.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XmIcon_H_
#define _XmIcon_H_
_XFUNCPROTOBEGIN
#include <Xfwf/Converters.h>
#ifndef XtNimage
#define XtNimage "image"
#endif
#ifndef XtCImage
#define XtCImage "Image"
#endif
#ifndef XtRIcon
#define XtRIcon "Icon"
#endif

#ifndef XtNactivate
#define XtNactivate "activate"
#endif
#ifndef XtCActivate
#define XtCActivate "Activate"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XmIconClassRec *XmIconWidgetClass;
typedef struct _XmIconRec *XmIconWidget;
externalref WidgetClass xmIconWidgetClass;
_XFUNCPROTOEND
#endif /*_XmIcon_H_*/
