/* Generated by wbuild from "HScrollb.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfHScrollbar_H_
#define _XfwfHScrollbar_H_

#include <Xfwf/Scrollbar.h>
_XFUNCPROTOBEGIN
typedef struct _XfwfHScrollbarClassRec *XfwfHScrollbarWidgetClass;
typedef struct _XfwfHScrollbarRec *XfwfHScrollbarWidget;
externalref WidgetClass xfwfHScrollbarWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfHScrollbar_H_*/
