/* Generated by wbuild from "Rows.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfRows_H_
#define _XfwfRows_H_
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
#ifndef XtNalignTop
#define XtNalignTop "alignTop"
#endif
#ifndef XtCAlignTop
#define XtCAlignTop "AlignTop"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

typedef struct _XfwfRowsClassRec *XfwfRowsWidgetClass;
typedef struct _XfwfRowsRec *XfwfRowsWidget;
externalref WidgetClass xfwfRowsWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfRows_H_*/
